# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine
WORKDIR /app

# Copy package files
COPY package.json bun.lock ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Install typescript globally since it's needed for the build (peer dependency)
RUN npm install --global typescript@^5.8.2

# Copy the rest of the source code
COPY . .

# Build the project
RUN npm run build

# The MCP server runs via stdio, so no port exposure is necessary.

CMD ["node", "build/index.js"]
